sonar.projectKey=polyglue-mobile-ide
sonar.organization=polyglue
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java,app/src/main/cpp
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.language=java,cpp

sonar.java.source=17
sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.threads=4

sonar.exclusions=**/third_party/**,**/*.pb.cc,**/*.pb.h
sonar.coverage.exclusions=**/ui/**,**/di/**
