package com.polyglue.ide.data.repository

import android.content.Context
import android.util.Log
import com.polyglue.ide.data.local.dao.BuildConfigDao
import com.polyglue.ide.data.local.entity.BuildConfigEntity
import com.polyglue.ide.data.local.entity.ProjectEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.withContext
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class BuildRepository(
    private val context: Context,
    private val buildConfigDao: BuildConfigDao
) {
    companion object { const val TAG = "BuildRepository" }

    private val _buildState = MutableStateFlow<BuildState>(BuildState.Idle)
    val buildState: StateFlow<BuildState> = _buildState

    sealed class BuildState {
        object Idle : BuildState()
        data class Preparing(val message: String) : BuildState()
        data class Compiling(val progress: Float) : BuildState()
        data class Packaging(val progress: Float) : BuildState()
        data class Signing(val progress: Float) : BuildState()
        data class Success(val apkPath: String) : BuildState()
        data class Error(val message: String) : BuildState()
    }

    suspend fun getBuildConfig(projectId: String): BuildConfigEntity? = buildConfigDao.getBuildConfig(projectId)

    suspend fun saveBuildConfig(config: BuildConfigEntity) {
        buildConfigDao.insertBuildConfig(config)
    }

    suspend fun buildAPK(project: ProjectEntity, scene: com.polyglue.ide.data.local.entity.SceneEntity): Result<String> = 
        withContext(Dispatchers.IO) {
            try {
                _buildState.value = BuildState.Preparing("Menyiapkan proyek...")
                val projectsDir = File(context.getExternalFilesDir(null), "projects/${project.id}")
                val buildDir = File(projectsDir, "build")
                buildDir.mkdirs()

                _buildState.value = BuildState.Preparing("Mengoptimasi aset...")
                val assetsDir = File(buildDir, "assets")
                assetsDir.mkdirs()
                val sourceAssets = File(projectsDir, "assets")
                if (sourceAssets.exists()) sourceAssets.copyRecursively(assetsDir, overwrite = true)

                _buildState.value = BuildState.Compiling(0.2f)
                val scriptsDir = File(buildDir, "scripts")
                scriptsDir.mkdirs()
                val luaScript = generateLuaFromScene(scene)
                File(scriptsDir, "main.lua").writeText(luaScript)

                _buildState.value = BuildState.Compiling(0.5f)
                val sceneJson = generateSceneJson(scene)
                File(buildDir, "scene.json").writeText(sceneJson)

                _buildState.value = BuildState.Packaging(0.7f)
                val apkPath = File(buildDir, "${project.name.replace(" ", "_")}.apk").absolutePath
                createPackage(buildDir, apkPath)

                _buildState.value = BuildState.Signing(0.9f)
                _buildState.value = BuildState.Success(apkPath)
                buildConfigDao.updateLastBuild(project.id, apkPath)
                Result.success(apkPath)
            } catch (e: Exception) {
                Log.e(TAG, "Build failed", e)
                _buildState.value = BuildState.Error(e.message ?: "Unknown error")
                Result.failure(e)
            }
        }

    private fun generateLuaFromScene(scene: com.polyglue.ide.data.local.entity.SceneEntity): String {
        return """
-- Auto-generated by PolyGlue Snippet Compiler
-- Scene: ${scene.name}

local entities = {}
local camera = { x = 0, y = 0, zoom = 1.0 }

function init()
    ${scene.luaScript}
end

function update(dt)
    for _, entity in ipairs(entities) do
        if entity.update then entity:update(dt) end
    end
    Camera.setPosition(camera.x, camera.y)
    Camera.setZoom(camera.zoom)
end

function render()
    for _, entity in ipairs(entities) do
        if entity.render then entity:render() end
    end
end

function onTouch(action, x, y, pointer)
    for _, entity in ipairs(entities) do
        if entity.onTouch then entity:onTouch(action, x, y, pointer) end
    end
end

init()
""".trimIndent()
    }

    private fun generateSceneJson(scene: com.polyglue.ide.data.local.entity.SceneEntity): String {
        return """
{
    "name": "${scene.name}",
    "width": ${scene.width},
    "height": ${scene.height},
    "backgroundColor": "${scene.backgroundColor}",
    "gravity": { "x": ${scene.gravityX}, "y": ${scene.gravityY} },
    "nodeGraph": ${scene.nodeGraphJson},
    "entities": ${scene.entitiesJson},
    "camera": ${scene.cameraJson},
    "tilemap": ${scene.tilemapJson},
    "lighting": ${scene.lightingJson}
}
""".trimIndent()
    }

    private fun createPackage(sourceDir: File, outputPath: String) {
        ZipOutputStream(File(outputPath).outputStream()).use { zos ->
            sourceDir.walkTopDown().forEach { file ->
                if (file.isFile) {
                    val entryName = file.relativeTo(sourceDir).path
                    zos.putNextEntry(ZipEntry(entryName))
                    file.inputStream().use { it.copyTo(zos) }
                    zos.closeEntry()
                }
            }
        }
    }

    fun resetState() { _buildState.value = BuildState.Idle }
}
