import json
from typing import Dict

def generate_lua_from_nodes(node_graph: Dict) -> str:
    code_lines = ["-- Auto-generated by PolyGlue Snippet Compiler", ""]
    for node in node_graph.get("nodes", []):
        node_type = node.get("type", "")
        if node_type.startswith("movement_"):
            code_lines.append(f"-- Movement: {node.get('id', '')}")
            code_lines.append("function updateMovement(dt)")
            code_lines.append("    local dir = Input.getAxis('Horizontal')")
            code_lines.append("    velocity.x = dir * 100")
            code_lines.append("end")
            code_lines.append("")
        elif node_type.startswith("ai_"):
            code_lines.append(f"-- AI: {node.get('id', '')}")
            code_lines.append("function updateAI(dt)")
            code_lines.append("    -- AI logic here")
            code_lines.append("end")
            code_lines.append("")
    code_lines.append("function update(dt)")
    code_lines.append("    updateMovement(dt)")
    code_lines.append("    updateAI(dt)")
    code_lines.append("end")
    return "\n".join(code_lines)

def generate_npc_name(style: str = "fantasy") -> str:
    import random
    prefixes = {"fantasy": ["Eld", "Thal", "Mor", "Gal", "Syl", "Kael", "Vor", "Lir"],
                "scifi": ["Zyx", "Nex", "Kor", "Vex", "Tyr", "Xen", "Jax", "Pyr"],
                "modern": ["Alex", "Sam", "Jordan", "Casey", "Taylor", "Morgan", "Riley"]}
    suffixes = {"fantasy": ["orin", "ara", "ion", "eth", "is", "an", "os", "ia"],
                "scifi": ["-7", " Prime", " X", " Unit", " Bot", " AI", " Core"],
                "modern": [" Smith", " Johnson", " Lee", " Chen", " Patel", " Kim"]}
    pre = random.choice(prefixes.get(style, prefixes["fantasy"]))
    suf = random.choice(suffixes.get(style, suffixes["fantasy"]))
    return pre + suf

def generate_dialogue(topic: str = "greeting") -> str:
    import random
    dialogues = {"greeting": ["Halo, petualang! Ada yang bisa kubantu?", "Selamat datang di desa kami!", "Hati-hati di luar sana, monster semakin banyak."],
                 "quest": ["Bisakah kau mengambilkan 10 ramuan untukku?", "Raja membutuhkan pahlawan. Kau tertarik?", "Anakku hilang di hutan. Tolong cari dia!"],
                 "shop": ["Lihat-lihat saja, jangan ragu!", "Barang terbaik di kota, harga terjangkau!", "Diskon 50% hari ini saja!"]}
    return random.choice(dialogues.get(topic, dialogues["greeting"]))
